name: Check / auto apply Black
on:
  push:
      branches:
          - dev
jobs:
  black:
    name: Check / auto apply black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check files using the black formatter
        uses: psf/black@stable
        id: black
        with:
          options: "."
        continue-on-error: true
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ":art: Format Python code with Black, and Bash code with Shfmt"
